### ISSUE TITLE
5.3 Creating the Matrix - getting NAs

### ISSUE THREAD

**Issue by aireste** [beanumber/baseball_R#11]
Having issues with creating the run expectancy matrix. 

**Here's my code**

data2016 %>%
  mutate(BASES = 
           paste(ifelse(BASE1_RUN_ID > '', 1, 0),
                 ifelse(BASE2_RUN_ID > '', 1, 0),
                 ifelse(BASE3_RUN_ID > '', 1, 0), sep = ""),
         STATE = paste(BASES, OUTS_CT)) -> 
  data2016

**This is the error warning message that I think is the root to my issue:** 
Warning messages:
1: Problem with `mutate()` column `BASES`.
ℹ `BASES = paste(...)`.
ℹ ‘>’ not meaningful for factors 
2: Problem with `mutate()` column `BASES`.
ℹ `BASES = paste(...)`.
ℹ ‘>’ not meaningful for factors 
3: Problem with `mutate()` column `BASES`.
ℹ `BASES = paste(...)`.
ℹ ‘>’ not meaningful for factors 

I have attached a screenshot of what it looks like in the data frame 

I have also attached what the output looks like in 5.5 when we analyze Jose Altuve 

<img width="133" alt="Screen Shot 2021-10-25 at 6 10 58 PM" src="https://user-images.githubusercontent.com/90633019/138778093-47fe4d4f-72c5-4928-a921-3ea65dfbfd4e.png">

<img width="285" alt="Screen Shot 2021-10-25 at 6 12 59 PM" src="https://user-images.githubusercontent.com/90633019/138778331-ba2a1681-d2e0-40c7-8004-1f583227bad0.png">

**Comment by bayesball** [comment]
I think the issue is that some of your variables in data2016 are factors and not character.  If you convert your factor variables to character (using command like d2016$BASES <- as.character(d2016$BASES)) things should work.
