### ISSUE TITLE
Chapter 8 lm function error

### ISSUE THREAD

**Issue by Josef-E** [beanumber/baseball_R#13]
Getting this error from chapter 8.4.1:

 Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases

I copied the code exactly from this website:

midcareers <- batting_2000 %>%
  group_by(playerID) %>%
  summarize(Midyear = (min(yearID) + max(yearID)) / 2,
            AB.total = first(Career.AB))
batting_2000 %>%
  inner_join(midcareers, by = "playerID") -> batting_2000

## ------------------------------------------------------------------------
models <- batting_2000 %>% 
  split(pull(., playerID)) %>%
  map(~lm(OPS ~ I(Age - 30) + I((Age - 30)^2), data = .)) %>%
  map_df(tidy, .id = "playerID")

I don't know why this error is appearing, everything else from the chapter has worked perfectly so far.

**Comment by Josef-E** [comment]
Figured it out. I still had NAs in multiple categories for some reason. In 8.3.4 after making the inner_join() I used this code:

batting_2000  <- batting_2000%>%
  replace_na(list(SB = 0, CS = 0, SH = 0, SF = 0, HPB = 0, OBP = 0, OPS = 0))

Then I ran:

models <- batting_2000 %>%
split(pull(., playerID)) %>%
map(~lm(OPS ~ I(Age - 30) + I((Age - 30)^2), data = .)) %>%
map_df(tidy, .id = "playerID")

Everything worked from there on out and the graphs all looked like what they do in the book with minor variations.

**Comment by bayesball** [comment]
Josef:

Glad you were able to figure it out.  The only issue I found was that the one dataset from the current version of the Lahman package is called People instead of Master.

Jim

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
