### ISSUE TITLE
Career Trajectory Chart

### ISSUE THREAD

**Issue by mlandry22** [beanumber/baseball_R#14]
The career trajectory chart and line fit should exclude active players. You can see the shape of the curve descends surprisingly rapidly. This is explained by using players who are in the middle of their career who have not yet hit their future peak.

I'm using the 2021 data, but the concept should be the same, and my "before" plot looks similar to the one in the book.

Original plot, from [L247 of trajectories.R](https://github.com/beanumber/baseball_R/blob/master/chapter_code/trajectories.R#L247)
![age_plot](https://user-images.githubusercontent.com/2976822/197694494-4a136499-43a0-4a79-ba34-754db4dfa30f.png)

After removing players whose final year was earlier than 2018
![age_plot_fixed](https://user-images.githubusercontent.com/2976822/197694760-3b4a1b52-6b7f-4c6b-b703-cd315fb34c2e.png)

This can be seen by calculating the final year for each playerID and plotting that per year and observing the large spike in the most recent year, which makes sense intuitively.
![count_of_players_by_last_year](https://user-images.githubusercontent.com/2976822/197694905-95bb6e8d-4fb0-4fb4-adcd-8da11fbd0939.png)

**Comment by beanumber** [comment]
@bayesball what do you think about this?

**Comment by bayesball** [comment]
Ben:

It would make sense to remove active players, but is there a simple flag
for that?  If we are using Lahman data, then the People dataset does
include the date of the last appearance.

I can check into this.

Jim

[image: Bowling Green State University] Jim Albert
Emeritus Professor,
Mathematics and Statistics
Bowling Green State University
***@***.***

**Comment by beanumber** [comment]
What about something like this?:

```
year(People$finalGame) == 2022
```

**Comment by bayesball** [comment]
Ben:

For current players, the People dataset just uses the last game in the 2022
season which won't work.

I am using a different filter that seems to work.  I'm checking the updated
graphs now.

Jim

[image: Bowling Green State University] Jim Albert
Emeritus Professor,
Mathematics and Statistics
Bowling Green State University
***@***.***
