### ISSUE TITLE
Chapter 5 code

### ISSUE THREAD

**Issue by dlock0715** [beanumber/baseball_R#3]
The following code for creating a run expectancy matrix in chapter 5 is giving me an error saying that "> not meaningful for factors" and failing to create the BASES and STATE variables

data2016 %>%
  mutate(BASES =
       paste(ifelse(BASE1_RUN_ID > ' ', 1, 0),
                 ifelse(BASE2_RUN_ID > ' ', 1, 0),
                 ifelse(BASE3_RUN_ID > ' ', 1, 0), sep = ' '),
         STATE = paste(BASES, OUTS_CT)) ->
  data2016

**Comment by bayesball** [comment]
Hi.

I think you need to convert all of your factor variables  to character.
For example, to convert BASE1_RUN to character, type

data2016$BASE1_ID <- as.character(data2016$BASE1_ID)

Then the code should work fine.

Jim

**Comment by beanumber** [comment]
This has been updated in the new edition:

https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#sec-runsexpectancy
