### ISSUE TITLE
Chapter 3, all 1998 retrosheet data file

### ISSUE THREAD

**Issue by jaredwheet** [beanumber/baseball_R#7]
Hi, I have been working through Chapter 3 on graphics.  I am on page 86 and it provides code to read the all1998 retrosheet data file, but that doesnt exist in the data folder.  Am I missing that file somewhere?

**Comment by bayesball** [comment]
Jered, there was an issue earlier due to the size of the file.  But I just
added it for you.  Jim

**Comment by beanumber** [comment]
Please see our new advice for downloading Retrosheet data by season:

https://beanumber.github.io/abdwr3e/A_retrosheet.html#sec-getretro
