### ISSUE TITLE
error message I don't understand 

### ISSUE THREAD

**Issue by Rmunter** [beanumber/baseball_R#8]
Hi I'm working my way through Analyzing Baseball with R. When working on the Chapter 2 first exercise, I'm getting the following error message even after typing straight from the answer given here (which is what I had done in the first place). What am I doing wrong?

> SB.Attempt = SB + CS
Error in SB + CS : non-numeric argument to binary operator

**Comment by beanumber** [comment]
It's hard to say without seeing what is in your R session. But in order for this to work, you have to have numeric vectors called `SB` and `CS` in your global environment.
