### ISSUE TITLE
Framing, PitchRx

### ISSUE THREAD

**Issue by rcarden71** [beanumber/baseball_R#9]
Working on chapter 7 and pitch framing. I and a few others have had issues scraping pitchrx. Is there a workaround?

**Comment by beanumber** [comment]
I don't know, but @cpsievert is the person who would:

https://github.com/cpsievert/pitchRx/issues/73

**Comment by cpsievert** [comment]
Does `remotes::install_github("cpsievert/pitchRx")`  help at all?

**Comment by beanumber** [comment]
`pitchRx` is dead. Long live Statcast via `baseballr`!

https://beanumber.github.io/abdwr3e/B_mlbam.html
